### ISSUE TITLE
Potential PAL emulation issue

### ISSUE THREAD

**Issue by gerliczer** [istvan-v/plus4emu#2]
I found an irregularity in the latest release of YAPE, which caused flickering that was not present either in its earlier releases or in plus4emu. I contacted the author to confirm the erroneous behaviour. It turned out that YAPE was in deed working incorrectly. However, running my test code on real hardware revealed that it caused a PAL phase inversion. Unfortunately, this effect doesn't really show up in plus4emu, or it is just me, who can't see it. Could you please notify me where I should send the test code to confirm if the issue is present? Send your message to the e-mail account I contacted you from before, please. It is the same that I registered on the Plus4World site.

**Comment by istvan-v** [comment]
You can post the test file here as an attachment. The effect is emulated, but it may not always look like on a real TV or monitor, since it depends on the display device how it reacts to the phase inverted signal if it covers a large part of the screen.
![inv](https://cloud.githubusercontent.com/assets/6630813/26443040/22ae33cc-4137-11e7-9e4b-7a5de2a9eff0.png)

**Comment by gerliczer** [comment]
Sorry, I wasn't reading carefully everything written in the page as I should have done it.

The phenomenon should be seen under the effect area while running the attached example. YAPE shows it and its author told me that it is also present on his real iron. plus4emu doesn't produce the PAL phase shifting issue in any of its OpenGL levels (0..3).

[flickr.zip](https://github.com/istvan-v/plus4emu/files/1033320/flickr.zip)

**Comment by istvan-v** [comment]
The OpenGL mode should not make a difference, phase inversion is always emulated, level 3 only enables filtering. It looks like there could be a timing issue, one of the writes to $FF1D sometimes happens right in cycle when the register is incremented.

It would be interesting to see what happens if the attached program is run on real hardware, it can be started with G 10FB. Also if the parameters loaded into Y,X,A at $1100 are changed from $00,$D1,$C4 to $00,$D0,$C2 or $00,$D1,$C6.

[inv_test.zip](https://github.com/istvan-v/plus4emu/files/1033468/inv_test.zip)

**Comment by gerliczer** [comment]
One kind Plus/4er made some tests on a real machine. The results are documented in the [Plus4World forum](http://plus4world.powweb.com/forum/33263#bottom). See the last few post in the linked topic, please.

**Comment by istvan-v** [comment]
Thanks, the test results do not seem to explain the problem, I will do more tests to find out what is causing it in flickrxo.prg.

**Comment by istvan-v** [comment]
After some more testing, it seems the problem is with the timing of the write of $78 to $FF1D, this happens in line $CD because there is a DMA in line $CC, however, the DMA is missing in plus4emu so the write is one line sooner and does not cause the inversion effect. Therefore, the issue is related to the logic that disables DMA at the end of the screen, I have a fix, but it will need to be tested on the real machine to make sure it is correct.

**Comment by gerliczer** [comment]
I think it is safe to assume that this issue is rectified.
